runtime: nodejs14

env_variables:
  PUBLIC_GCP_BUCKET: "rss-for-email-dev-public"
  EMAIL_DOMAIN: "rss-for.email"
  BASE_URL: "https://rss-for-email-dev.ts.r.appspot.com"

handlers:
- url: /static
  static_dir: static
